name: repo
version: 0.0.1
description: A simple console application.
#dependencies:
#  foo_bar: '>=1.0.0 <2.0.0'
dependencies:
  github: '>=3.0.0 <4.0.0'

  args: '>=0.13.6 <0.14.0'
  path: '>=1.3.9 <2.0.0'
executable:
  repo: null
